---
title: "Introduction to Data Visualization in R"
format:
  html:
   toc: true
---

# Introduction to Data Visualization in R

Workshop materials and instructions for the *Introduction to Data Visualization in R* virtual workshop, led by JHU Data Services.

This workshop introduces data visualization in R using base R and `ggplot2`. In this hands-on workshop, we cover design concepts of data visualization and popular R packages, before diving into creating data visualizations for a prepared dataset using base R and ggplot2.

## Post-Class Survey

If you have taken the live webinar for this class, please take this survey: [Intro to Data Vis in R Survey](http://bit.ly/data-vis-r-survey)

## Workshop Materials

### Presentation Slides

- [Presentation Slides (PDF)](PresentationMaterials/IntroDataVisR.pdf)

### Completed Code

- [Base R](In-ClassScripts/lesson-1-base-r.qmd)
- [ggplot2](In-ClassScripts/lesson-2-ggplot2.qmd)

### Cheatsheets

- [Base Graphics Cheatsheet](Resources/BaseGraphicsCheatsheet.pdf)
- [ggplot2 Cheatsheet](Resources/ggplot2Cheatsheet.pdf)

## JHU Data Services

Website: [dataservices.library.jhu.edu](https://dataservices.library.jhu.edu/)
Contact us: [dataservices@jhu.edu](mailto:dataservices@jhu.edu)

JHU Data Services, part of the Johns Hopkins University Sheridan Libraries, helps the JHU community find, use, visualize, manage, and share data. We offer live webinars and self-paced online trainings on computational research and coding, GIS, data management, data visualization, and more. [See all of our training topics on our website.](https://dataservices.library.jhu.edu/training-workshops/)

## License and Terms of Use

The presentation materials are licensed under a [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0)](https://creativecommons.org/licenses/by-nc-sa/4.0/), attributable to [Data Services](https://dataservices.library.jhu.edu/), Johns Hopkins University.

See [LICENSE](LICENSE) file for additional code licensing and re-use information.

The images, external resources, and cheatsheets linked in this repository may have other licenses and terms of use.

## Citation

Please cite this material as:
Johns Hopkins University Data Services. March 4, 2026. [Introduction to Data Visualization in R](https://github.com/jhu-data-services/intro-to-data-visualization-in-r)
